apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceapp-deploy
  annotations:
    kubernetes.io/change-cause: "deploying v2"
spec:
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "100%"
  selector:
    matchLabels:
      app:  orderapp-service
  replicas: 4
  template:
    metadata:
      labels:
        app:  orderapp-service
    spec:
      containers:
      - name:  orderapp-service
        image: pes2ug21cs254lasyatalasila/orderapp:1.2
        ports:
        - name: "app-port"
          containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: oderapp-svc
spec:
  type: NodePort
  selector:
    app: orderapp-service
  ports:
  - port: 8081 #port that we want to expose for pod
    targetPort: 8081 #port inside container
    nodePort: 30001 # this the host port
