spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productapp1
      repositories:
        enabled: true
  application:
    name: productapp
server:
  port: 8080

logging:
  level:
    org:
    springframework:
      data:
        mongodb:
          repository:
            query: debug
          core:
            repository:
              query: debug
