spring:
  application:
    name: BasicAuth
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/koerberbookstore?useSSL=false
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org:
      springframework:
        web: DEBUG
