apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapp-deploy
  annotations:
    kubernetes.io/change-cause: "deploying v4"
spec:
  minReadySeconds: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app:  orderapp-service
  replicas: 4
  template:
    metadata:
      labels:
        app:  orderapp-service
    spec:
      containers:
      - name:  orderapp-service
        image: pes2ug21cs254lasyatalasila/orderapp:1.4
        ports:
        - name: "app-port"
          containerPort: 8081