apiVersion: v1
kind: Pod
metadata:
  name: bookapp-pod
  labels:
    app: bookapp
spec:
  containers:
    - name: bookstore
      image: pes2ug21cs254lasyatalasila/bookapp:1.1
      ports:
        - containerPort: 8090
