spring:
  application:
    name: cc
  profiles:
    active: test
  config:
    import: "optional:configserver:http://localhost:8090"
  cloud:
    openfeign:
      circuitBreaker:
        enabled: true
# openfeign won't support circuit breaker is default disabled
server:
  port: 8100

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        wait-duration-in-half-open-state: 5s
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"