apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookapp-d
  annotations:   
    kubernetes.io/change-cause: "deploying v2"
spec:
  minReadySeconds: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bookstore-app
  replicas: 4
  template:
    metadata:
      labels:  
        app: bookstore-app
    spec:
      containers:  
        - name: bookstore
          image: pes2ug21cs254lasyatalasila/bookapp:1.2
